@api_url = http://localhost:4000

### Get all the videos
GET {{api_url}}/api/videos

### Get video by id
GET {{api_url}}/api/videos/63c5ed4043026cca7d0105cb

### Create video
POST {{api_url}}/api/videos
Content-Type: application/json

{
  "title": "Sherlock",
  "description": "Sherlock Series",
  "url": "https://www.youtube.com/watch?v=-bBHT158E0s"
}

### Update video
PUT {{api_url}}/api/videos/63c5ed4043026cca7d0105cb
Content-Type: application/json

{
  "title": "Sherlock modified twice"
}

### Delete video
DELETE {{api_url}}/api/videos/63c5ed4043026cca7d0105cb
